### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ybxgood** [CB2Git/STelBook#2]
请问你这个项目可以导入Android Studio后，直接运行吗？

**Comment by CB2Git** [comment]
不可以吧，我把后台设置为不活跃了，而且貌似只能兼容4.0及以下的

**Comment by ybxgood** [comment]
我折腾了一天，已经可以运行了，谢谢分享。

**Comment by CB2Git** [comment]
在高版本的android系统上面可能报出权限错误，因为获取通讯录在高版本的上面需要动态获取权限

**Comment by ybxgood** [comment]
嗯，这个设置一下就好了。
